/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mJni_JniClient */

#ifndef _Included_mJni_JniClient
#define _Included_mJni_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mJni_JniClient
 * Method:    addStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mJni_JniClient_addStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     mJni_JniClient
 * Method:    addInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_mJni_JniClient_addInt
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
